ab_parallel_testing_homepage:
    pattern:  /
    defaults: { _controller: ABParallelTestingBundle:Default:index }

ab_parallel_testing_update:
    pattern:  /update
    defaults: { _controller: ABParallelTestingBundle:Default:update }

ab_parallel_testing_results:
    pattern:  /results
    defaults: { _controller: ABParallelTestingBundle:Default:charts, type: 1 }

ab_parallel_testing_speedup:
    pattern:  /speedup
    defaults: { _controller: ABParallelTestingBundle:Default:charts, type: 2 }