ab_parallel_testing_homepage:
    pattern:  /
    defaults: { _controller: ABParallelTestingBundle:Default:index }

ab_parallel_testing_update:
    pattern:  /update
    defaults: { _controller: ABParallelTestingBundle:Default:update }

ab_parallel_testing_charts:
    pattern:  /charts
    defaults: { _controller: ABParallelTestingBundle:Default:charts }